name: soko
description: Application des ventes en ligne.
# description: A new Flutter project.
publish_to: "none"

version: 2.2.0+26

environment:
  sdk: ">=3.5.0 <4.2.0"
  flutter: 3.24.0

dependencies:
  flutter:
    sdk: flutter

   # flutter_slidable: any
  http: ^0.13.3
  shimmer: ^3.0.0 # Ajoutez ou mettez Ã  jour cette ligne
  cached_network_image: ^3.2.0
  shared_preferences: ^2.0.8
  # flutter_secure_storage: ^5.0.2
  provider: ^6.0.2
  intl: ^0.17.0  # Pour le formatage des prix
  google_fonts :
  image_picker :
  url_launcher: ^6.0.12
  # share_plus: ^2.1.4
  flutter_html: 
  dio: ^5.0.0
  html_unescape :
  path_provider: ^2.1.1
  firebase_auth :
  cloud_firestore :
  google_sign_in: ^6.1.5
  geolocator: ^11.0.1
  geocoding :
  permission_handler: ^11.0.1
  sign_in_with_apple: ^7.0.1
  crypto: ^3.0.7
dev_dependencies:
  flutter_test:
    sdk: flutter

#  change_app_package_name: ^1.1.0
#  flutter_launcher_icons:
  flutter_lints: 5.0.0
  flutter_launcher_icons: ^0.14.4
#  build_runner:
#  flutter_gen_runner:
#  rename_app: ^1.6.1
#  dart_code_metrics: 5.7.6

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/logo.png"

# flutter_gen:
#   output: lib/custom_assets/ # Optional (default: lib/gen/)
#   line_length: 80 # Optional (default: 80)

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # # fonts:
  # fonts:
  #   - family: AgencyFB-Bold
  #     fonts:
  #       - asset: fonts/AgencyFB-Bold.ttf

  assets:
    - assets/
